import { createElement } from 'lwc';
import Lg_ReC_View_Form from 'c/lg_ReC_View_Form';

describe('c-lg-re-c-view-form', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lg-re-c-view-form', {
            is: Lg_ReC_View_Form
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});